project_id = "dvjifzjaqyjnnstnzweg"

[functions.chat]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.search-hotels]
verify_jwt = false

[functions.search-flights]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-booking-sms]
verify_jwt = false

[functions.send-booking-whatsapp]
verify_jwt = false

[functions.create-booking-payment]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false
