project_id = "dvjifzjaqyjnnstnzweg"

[functions.chat]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.search-hotels]
verify_jwt = false

[functions.search-flights]
verify_jwt = false
